version: '3'

services:
  strapi-server:
    image: idea2app/strapi-server
    environment:
      - NODE_ENV=production
      - PORT=1337
    ports:
      - 1337:1337
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:1337/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
